USE [master]
GO

CREATE DATABASE [ZalexHR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ZalexHR', FILENAME = N'**' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ZalexHR_log', FILENAME = N'**' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ZalexHR].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ZalexHR] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ZalexHR] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ZalexHR] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ZalexHR] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ZalexHR] SET ARITHABORT OFF 
GO

ALTER DATABASE [ZalexHR] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ZalexHR] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ZalexHR] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ZalexHR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ZalexHR] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ZalexHR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ZalexHR] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ZalexHR] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ZalexHR] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ZalexHR] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ZalexHR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ZalexHR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ZalexHR] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ZalexHR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ZalexHR] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ZalexHR] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ZalexHR] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ZalexHR] SET RECOVERY FULL 
GO

ALTER DATABASE [ZalexHR] SET  MULTI_USER 
GO

ALTER DATABASE [ZalexHR] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ZalexHR] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ZalexHR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ZalexHR] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ZalexHR] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ZalexHR] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ZalexHR] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ZalexHR] SET  READ_WRITE 
GO


